######################################################################
# Automatically generated by qmake (3.0) ?? 3? 15 00:43:51 2016
######################################################################

TEMPLATE = app
TARGET = WifiAssist
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h wdevices.h wifi.h wsettings.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp wdevices.cpp wifi.cpp wsettings.cpp
RESOURCES += icon.qrc icon_edit2.qrc
